export const projects = [
    {
      id: 1,
      title: "AI Tools Showcase",
      description: "A full-stack AI tools showcase with authentication and API integration.",
      image: "/images/Project1.png", 
      link: "https://github.com/mahnoortufailse/ai-tools-showcase.git",
      stack: "Full Stack",
      features: ["Authentication", "API Integration"],
    },
    {
      id: 2,
      title: "Interior Design Website",
      description: "A responsive frontend project for an interior design company.",
      image: "/images/Project2.png",
      link: "https://github.com/mahnoortufailse/Interior_Design-Frontend-Project.git",
      stack: "Frontend Only",
      features: ["Responsive Design"],
    },
    {
      id: 3,
      title: "Pharmacy Finder",
      description: "A frontend project with some backend implementation for finding pharmacies.",
      image: "/images/Project3.png",
      link: "https://github.com/mahnoortufailse/pharmacy-finder.git",
      stack: "Frontend & Some Backend",
      features: ["Frontend Design", "Basic Backend Implementation"],
    },
    {
      id: 4,
      title: "4 Rays",
      description: "A web platform with frontend design, backend implementation, and authentication.",
      image: "/images/Project4.png",
      link: "https://github.com/mahnoortufailse/4rays.git",
      stack: "Full Stack",
      features: ["Frontend", "Backend", "Authentication"],
    },
    {
      id: 5,
      title: "Bookstore",
      description: "A bookstore website with a responsive design and authentication.",
      image: "/images/Project5.png",
      link: "https://github.com/mahnoortufailse/bookstore.git",
      stack: "Frontend & Authentication",
      features: ["Responsive Design", "Authentication"],
    },
    {
      id: 6,
      title: "Artex",
      description: "A responsive design project for an art portfolio website.",
      image: "/images/Project6.png",
      link: "https://github.com/mahnoortufailse/artex.git",
      stack: "Frontend Only",
      features: ["Responsive Design"],
    },
  ];
  